"""Added products data

Revision ID: 807fb6266a44
Revises: e0013bd64994
Create Date: 2019-11-17 15:45:55.306111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '807fb6266a44'
down_revision = 'e0013bd64994'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("INSERT INTO products (name, price) values ('apple', 1);")
    op.execute("INSERT INTO products (name, price) values ('banana', 1.1);")
    op.execute("INSERT INTO products (name, price) values ('kiwi', 3);")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM products;")
    # ### end Alembic commands ###
